export default class ProcessSpells {
	static parse(jsonData) {
		return jsonData.map(spell => ({
			name: spell.name,
			school: spell.school,
			subschool: spell.subschool,
			descriptor: spell.descriptor,
			components: spell.components,
			range: spell.range,
			effect: spell.effect,
			duration: spell.duration,
			shapeable: +spell.shapeable === 1,
			dismissible: +spell.dismissible === 1,
			description: spell.description,
			source: spell.source,
			verbal: +spell.verbal === 1,
			somatic: +spell.somatic === 1,
			material: +spell.material === 1,
			focus: +spell.focus === 1,
			sor: +spell.sor,
			wiz: +spell.wiz,
			cleric: +spell.cleric,
			druid: +spell.druid,
			ranger: +spell.ranger,
			bard: +spell.bard,
			paladin: +spell.paladin,
			alchemist: +spell.alchemist,
			summoner: +spell.summoner,
			witch: +spell.witch,
			inquisitor: +spell.inquisitor,
			oracle: +spell.oracle,
			antipaladin: +spell.antipaladin,
			magus: +spell.magus,
			adept: +spell.adept,
			bloodrager: +spell.bloodrager,
			shaman: +spell.shaman,
			psychic: +spell.psychic,
			medium: +spell.medium,
			mesmerist: +spell.mesmerist,
			occultist: +spell.occultist,
			spiritualist: +spell.spiritualist,
			skald: +spell.skald,
			investigator: +spell.investigator,
			hunter: +spell.hunter,
			summonerUnchained: +spell.summoner_unchained,
			acid: +spell.acid === 1,
			air: +spell.air === 1,
			chaotic: +spell.chaotic === 1,
			cold: +spell.cold === 1,
			curse: +spell.curse === 1,
			darkness: +spell.darkness === 1,
			death: +spell.death === 1,
			disease: +spell.disease === 1,
			earth: +spell.earth === 1,
			electricity: +spell.electricity === 1,
			emotion: +spell.emotion === 1,
			evil: +spell.evil === 1,
			fear: +spell.fear === 1,
			fire: +spell.fire === 1,
			force: +spell.force === 1,
			good: +spell.good === 1,
			lawful: +spell.lawful === 1,
			light: +spell.light === 1,
			pain: +spell.pain === 1,
			poison: +spell.poison === 1,
			shadow: +spell.shadow === 1,
			sonic: +spell.sonic === 1,
			water: +spell.water === 1,
			mythic: +spell.mythic === 1,
			ruse: +spell.ruse === 1,
			draconic: +spell.draconic === 1,
			meditative: +spell.meditative === 1,
			spellLevel: spell.spell_level,
			castingTime: spell.casting_time,
			savingThrow: spell.savingThrow,
			spellResistence: spell.spell_resistence,
			shortDescription: spell.short_description,
			costlyComponents: +spell.costly_components === 1,
			divineFocus: +spell.divine_focus === 1,
			spellLikeAbilityLevel: +spell.SLA_Level,
			languageDependent: +spell.language_dependent === 1,
			mindAffecting: +spell.mind_affecting === 1,
			materialCosts: +spell.material_costs,
			id: +spell.id,
		}));
	}
}