export const SpellType = `
  type Spell {
    name: String
    school: String
    subschool: String
    descriptor: String
    components: String
    range: String
    effect: String
    duration: String
    shapeable: Boolean
    dismissible: Boolean
    description: String
    source: String
    verbal: Boolean
    somatic: Boolean
    material: Boolean
    focus: Boolean
    sor: Int
    wiz: Int
    cleric: Int
    druid: Int
    ranger: Int
    bard: Int
    paladin: Int
    alchemist: Int
    summoner: Int
    witch: Int
    inquisitor: Int
    oracle: Int
    antipaladin: Int
    magus: Int
    adept: Int
    bloodrager: Int
    shaman: Int
    psychic: Int
    medium: Int
    mesmerist: Int
    occultist: Int
    spiritualist: Int
    skald: Int
    investigator: Int
    hunter: Int
    summonerUnchained: Int
    acid: Boolean
    air: Boolean
    chaotic: Boolean
    cold: Boolean
    curse: Boolean
    darkness: Boolean
    death: Boolean
    disease: Boolean
    earth: Boolean
    electricity: Boolean
    emotion: Boolean
    evil: Boolean
    fear: Boolean
    fire: Boolean
    force: Boolean
    good: Boolean
    lawful: Boolean
    light: Boolean
    pain: Boolean
    poison: Boolean
    shadow: Boolean
    sonic: Boolean
    water: Boolean
    mythic: Boolean
    ruse: Boolean
    draconic: Boolean
    meditative: Boolean
    spellLevel: String
    castingTime: String
    savingThrow: String
    spellResistence: String
    shortDescription: String
    costlyComponents: Boolean
    divineFocus: Boolean
    spellLikeAbilityLevel: Int
    languageDependent: Boolean
    mindAffecting: Boolean
    materialCosts: Int
    id: Int
  }
`;